In [4]:
import pandas as pd
import numpy as np

In [5]:
datafile = pd.read_csv('cardiocleaned.csv')   #reading the cleaned dataset

label = datafile['cardio'].values   #  output y is separated in a list called as label
data = datafile.drop(['cardio'], axis = 1)    #input x is separated in form of Dataframe called as data 
datafile

age  gender  height  weight  ap_hi  ap_lo   cholesterol  \
0      18393    male     168    62.0    110     80       chl_avg   
1      20228  female     156    85.0    140     90      chl_high   
2      18857  female     165    64.0    130     70      chl_high   
3      17623    male     169    82.0    150    100       chl_avg   
4      17474  female     156    56.0    100     60       chl_avg   
...      ...     ...     ...     ...    ...    ...           ...   
67741  19240    male     168    76.0    120     80       chl_avg   
67742  22601  female     158   126.0    140     90  chl_aboveavg   
67743  19066    male     183   105.0    180     90      chl_high   
67744  22431  female     163    72.0    135     80       chl_avg   
67745  20540  female     170    72.0    120     80  chl_aboveavg   

               gluc  smoke  alco  active  cardio  
0           glc_avg      0     0       1       0  
1           glc_avg      0     0       1       1  
2           glc_avg      0     0       0       1  
3           glc_avg      0     0       1       1  
4           glc_avg      0     0       0       0  
...             ...    ...   ...     ...     ...  
67741       glc_avg      1     0       1       0  
67742  glc_aboveavg      0     0       1       1  
67743       glc_avg      0     1       0       1  
67744  glc_aboveavg      0     0       0       1  
67745       glc_avg      0     0       1       0  

[67746 rows x 12 columns]

In [6]:
type(label)

numpy.ndarray

In [7]:
type(data)

pandas.core.frame.DataFrame

In [8]:
# split data into training, validation, testing data
from sklearn.model_selection import train_test_split   #class to split data

inputtrain, inputtest, outputtrain, outputtest = train_test_split(data, label, test_size = 0.2, stratify = label)
# inputtrain, inputcv, outputtrain, outputcv = train_test_split(inputtrain, outputtrain, test_size = 0.2, stratify = outputtrain)
# # cv = cross- validation


In [9]:
inputtrain.shape

(54196, 11)

In [10]:
# inputcv.shape

In [11]:
inputtest.shape

(13550, 11)

In [12]:
outputtrain.shape

(54196,)

In [13]:
outputtest.shape

(13550,)

In [14]:
type(inputtrain), type(outputtrain)

(pandas.core.frame.DataFrame, numpy.ndarray)

In [15]:
inputtrain

age  gender  height  weight  ap_hi  ap_lo cholesterol          gluc  \
11563  16976    male     174    76.0    130     80     chl_avg       glc_avg   
22219  17655  female     164    90.0    140     80    chl_high       glc_avg   
65398  20430    male     170    63.0    120     80     chl_avg       glc_avg   
19180  18417    male     173   101.0    135     90    chl_high       glc_avg   
46801  17365  female     156    79.0    110     70     chl_avg       glc_avg   
...      ...     ...     ...     ...    ...    ...         ...           ...   
31413  20902  female     170    85.0    140     80    chl_high  glc_aboveavg   
44715  15401  female     156    62.0     80     60     chl_avg       glc_avg   
62212  14606  female     165    74.0    120     70     chl_avg       glc_avg   
8260   18261    male     168    72.0    130     90     chl_avg       glc_avg   
38417  20217    male     152    50.0    100     70     chl_avg       glc_avg   

       smoke  alco  active  
11563      0     0       1  
22219      0     0       0  
65398      0     0       1  
19180      0     1       1  
46801      1     0       0  
...      ...   ...     ...  
31413      0     0       1  
44715      0     0       0  
62212      0     0       0  
8260       0     0       1  
38417      1     0       1  

[54196 rows x 11 columns]

In [16]:
#scaling age (in days) (Numerical data) using Min-Max Scaler

from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()
scale.fit(inputtrain['age'].values.reshape(-1,1)) 

inputtrain_age = scale.transform(inputtrain[['age']])  
# inputcv_age = scale.transform(inputcv['age'].values.reshape(-1,1))
inputtest_age = scale.transform(inputtest['age'].values.reshape(-1,1))

/home/komal/anaconda3/envs/myenv/lib/python3.12/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


In [17]:
type(inputtrain_age)

numpy.ndarray

In [18]:
inputtrain_age.shape

(54196, 1)

In [19]:
# inputcv_age.shape

In [20]:
type(outputtrain)

numpy.ndarray

In [21]:
outputtrain.shape

(54196,)

In [22]:
# convert gender (categorical data) into One Hot Encoding

from sklearn.feature_extraction.text import CountVectorizer  

vec = CountVectorizer()
vec.fit(inputtrain['gender'].values)

inputtrain_gender = vec.transform(inputtrain['gender'].values)  
# inputcv_gender = vec.transform(inputcv['gender'].values)
inputtest_gender = vec.transform(inputtest['gender'].values)


In [23]:
inputtrain_gender

<54196x2 sparse matrix of type '<class 'numpy.int64'>'
	with 54196 stored elements in Compressed Sparse Row format>

In [24]:
type(inputtrain_gender)   #reshape(-1,1) convert sparse csr matrix into nparray

scipy.sparse._csr.csr_matrix

In [25]:
type(inputtrain_gender.toarray())

numpy.ndarray

In [26]:
inputtrain_gender.toarray()

array([[0, 1],
       [1, 0],
       [0, 1],
       ...,
       [1, 0],
       [0, 1],
       [0, 1]])

In [27]:
inputtrain_gender.toarray().shape

(54196, 2)

In [28]:
inputtrain_gender.shape

(54196, 2)

In [29]:
#scaling height (in cm) (Numerical data) using Min-Max Scaler

#from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()
scale.fit(inputtrain['height'].values.reshape(-1,1)) 

inputtrain_height = scale.transform(inputtrain['height'].values.reshape(-1,1))  
# inputcv_height = scale.transform(inputcv['height'].values.reshape(-1,1))
inputtest_height = scale.transform(inputtest['height'].values.reshape(-1,1))

In [30]:
type(inputtrain_height)

numpy.ndarray

In [31]:
inputtrain_height.shape

(54196, 1)

In [32]:
inputtrain_height

array([[0.41538462],
       [0.33846154],
       [0.38461538],
       ...,
       [0.34615385],
       [0.36923077],
       [0.24615385]])

In [33]:
#scaling weight (in kg) (Numerical data) using Min-Max Scaler

#from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()
scale.fit(inputtrain['weight'].values.reshape(-1,1)) 

inputtrain_weight = scale.transform(inputtrain['weight'].values.reshape(-1,1))  
# inputcv_weight = scale.transform(inputcv['weight'].values.reshape(-1,1))
inputtest_weight = scale.transform(inputtest['weight'].values.reshape(-1,1))

In [34]:
#scaling ap_lo (Numerical data) using Min-Max Scaler

#from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()
scale.fit(inputtrain['ap_lo'].values.reshape(-1,1)) 

inputtrain_ap_lo = scale.transform(inputtrain['ap_lo'].values.reshape(-1,1))  
# inputcv_ap_lo = scale.transform(inputcv['ap_lo'].values.reshape(-1,1))
inputtest_ap_lo = scale.transform(inputtest['ap_lo'].values.reshape(-1,1))

In [35]:
# convert cholesterol (categorical data) into One Hot Encoding

#from sklearn.feature_extraction.text import CountVectorizer  

vec = CountVectorizer()
vec.fit(inputtrain['cholesterol'].values)

inputtrain_cholesterol = vec.transform(inputtrain['cholesterol'].values)  
# inputcv_cholesterol = vec.transform(inputcv['cholesterol'].values)
inputtest_cholesterol = vec.transform(inputtest['cholesterol'].values)

In [36]:
# convert glucose (categorical data) into One Hot Encoding

#from sklearn.feature_extraction.text import CountVectorizer  

vec = CountVectorizer()
vec.fit(inputtrain['gluc'].values)

inputtrain_gluc = vec.transform(inputtrain['gluc'].values)  
# inputcv_gluc = vec.transform(inputcv['gluc'].values)
inputtest_gluc = vec.transform(inputtest['gluc'].values)

In [37]:
# smoke (categorical data) binary only 0/1 (Yes/No) hence no need to convert into One Hot Encoding 

#just converting sparse csr matrix form in np array form

inputtrain_smoke = inputtrain['smoke'].values.reshape(-1,1)
# inputcv_smoke = inputcv['smoke'].values.reshape(-1,1)
inputtest_smoke = inputtest['smoke'].values.reshape(-1,1)

In [38]:
# active, smoke, alcohol (categorical data) binary only 0/1 (Yes/No) hence no need to convert into One Hot Encoding 

#just converting sparse csr matrix form in np array form

inputtrain_active = inputtrain['active'].values.reshape(-1,1)
inputtest_active = inputtest['active'].values.reshape(-1,1)

inputtrain_smoke = inputtrain['smoke'].values.reshape(-1,1)
inputtest_smoke = inputtest['smoke'].values.reshape(-1,1)

inputtrain_alco = inputtrain['alco'].values.reshape(-1,1)
inputtest_alco = inputtest['alco'].values.reshape(-1,1)

In [39]:
inputtrain

age  gender  height  weight  ap_hi  ap_lo cholesterol          gluc  \
11563  16976    male     174    76.0    130     80     chl_avg       glc_avg   
22219  17655  female     164    90.0    140     80    chl_high       glc_avg   
65398  20430    male     170    63.0    120     80     chl_avg       glc_avg   
19180  18417    male     173   101.0    135     90    chl_high       glc_avg   
46801  17365  female     156    79.0    110     70     chl_avg       glc_avg   
...      ...     ...     ...     ...    ...    ...         ...           ...   
31413  20902  female     170    85.0    140     80    chl_high  glc_aboveavg   
44715  15401  female     156    62.0     80     60     chl_avg       glc_avg   
62212  14606  female     165    74.0    120     70     chl_avg       glc_avg   
8260   18261    male     168    72.0    130     90     chl_avg       glc_avg   
38417  20217    male     152    50.0    100     70     chl_avg       glc_avg   

       smoke  alco  active  
11563      0     0       1  
22219      0     0       0  
65398      0     0       1  
19180      0     1       1  
46801      1     0       0  
...      ...   ...     ...  
31413      0     0       1  
44715      0     0       0  
62212      0     0       0  
8260       0     0       1  
38417      1     0       1  

[54196 rows x 11 columns]

In [40]:
type(inputtrain_smoke)

numpy.ndarray

In [41]:
inputtrain_smoke.shape

(54196, 1)

In [42]:
type(inputtrain_active)

numpy.ndarray

In [43]:
inputtrain_active.shape

(54196, 1)

In [100]:
# stack arrays horizontally

from scipy.sparse import hstack

input_train = hstack((inputtrain_age, inputtrain_gender, inputtrain_height, inputtrain_weight, inputtrain_cholesterol, inputtrain_gluc, inputtrain_smoke , inputtrain_alco,inputtrain_active))
# cv = hstack((inputcv_age, inputcv_gender, inputcv_height, inputcv_weight, inputcv_cholesterol, inputcv_gluc, inputcv_active))
input_test = hstack((inputtest_age, inputtest_gender, inputtest_height, inputtest_weight, inputtest_cholesterol, inputtest_gluc,inputtest_smoke, inputtest_alco , inputtest_active))

In [101]:
input_train

<54196x14 sparse matrix of type '<class 'numpy.float64'>'
	with 375956 stored elements in COOrdinate format>

In [102]:
#input_train.columns()

In [103]:
input_train = input_train.toarray()
input_test = input_test.toarray()

In [104]:
type(input_train)

numpy.ndarray

In [105]:
outputtrain

array([1, 0, 0, ..., 0, 0, 0])

In [106]:
input_train.shape   #input data

(54196, 14)

In [107]:
# cv.shape     #input data

In [108]:
input_test.shape     #input data

(13550, 14)

In [109]:
outputtrain.shape, outputtest.shape

((54196,), (13550, 1))

In [110]:
type(outputtrain), type(outputtest)

(numpy.ndarray, numpy.ndarray)

In [111]:
outputtrain = outputtrain.reshape(-1,1)
outputtest = outputtest.reshape(-1,1)

In [112]:
outputtrain = outputtrain.ravel()

In [113]:
type(outputtrain), type(outputtest)

(numpy.ndarray, numpy.ndarray)

In [114]:
outputtrain.shape, outputtest.shape

((54196,), (13550, 1))

In [115]:
###### Decision Tree

In [116]:
from sklearn.tree import DecisionTreeClassifier , plot_tree
import matplotlib.pyplot as plt

In [117]:
dtree = DecisionTreeClassifier(max_depth = 7, min_samples_split = 400)

In [118]:
dtree.fit(input_train,outputtrain)

DecisionTreeClassifier(max_depth=7, min_samples_split=400)

In [123]:
plt.figure(figsize = (20,10))
plot_tree = (dtree)
plt.show()

<Figure size 2000x1000 with 0 Axes>

In [125]:
y_pred_train = dtree.predict_proba(input_train)[:,1]
y_pred_test = dtree.predict_proba(input_test)[:,1]

In [127]:
# calculate accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_pred_test,outputtest)

ValueError: Classification metrics can't handle a mix of continuous and binary targets