In [1]:
import pandas as pd
import numpy as np

In [2]:
datafile = pd.read_csv('cardiocleaned.csv')   #reading the cleaned dataset

label = datafile['cardio'].values   #  output y is separated in a list called as label
data = datafile.drop(['cardio'], axis = 1)    #input x is separated in form of Dataframe called as data 
datafile

age  gender  height  weight  ap_hi  ap_lo   cholesterol  \
0      18393    male     168    62.0    110     80       chl_avg   
1      20228  female     156    85.0    140     90      chl_high   
2      18857  female     165    64.0    130     70      chl_high   
3      17623    male     169    82.0    150    100       chl_avg   
4      17474  female     156    56.0    100     60       chl_avg   
...      ...     ...     ...     ...    ...    ...           ...   
67741  19240    male     168    76.0    120     80       chl_avg   
67742  22601  female     158   126.0    140     90  chl_aboveavg   
67743  19066    male     183   105.0    180     90      chl_high   
67744  22431  female     163    72.0    135     80       chl_avg   
67745  20540  female     170    72.0    120     80  chl_aboveavg   

               gluc  smoke  alco  active  cardio  
0           glc_avg      0     0       1       0  
1           glc_avg      0     0       1       1  
2           glc_avg      0     0       0       1  
3           glc_avg      0     0       1       1  
4           glc_avg      0     0       0       0  
...             ...    ...   ...     ...     ...  
67741       glc_avg      1     0       1       0  
67742  glc_aboveavg      0     0       1       1  
67743       glc_avg      0     1       0       1  
67744  glc_aboveavg      0     0       0       1  
67745       glc_avg      0     0       1       0  

[67746 rows x 12 columns]

In [3]:
type(label)

numpy.ndarray

In [4]:
type(data)

pandas.core.frame.DataFrame

In [5]:
# split data into training, validation, testing data
from sklearn.model_selection import train_test_split   #class to split data

inputtrain, inputtest, outputtrain, outputtest = train_test_split(data, label, test_size = 0.2, stratify = label)
# inputtrain, inputcv, outputtrain, outputcv = train_test_split(inputtrain, outputtrain, test_size = 0.2, stratify = outputtrain)
# # cv = cross- validation


In [6]:
inputtrain.shape

(54196, 11)

In [7]:
# inputcv.shape

In [8]:
inputtest.shape

(13550, 11)

In [9]:
outputtrain.shape

(54196,)

In [10]:
outputtest.shape

(13550,)

In [11]:
type(inputtrain), type(outputtrain)

(pandas.core.frame.DataFrame, numpy.ndarray)

In [12]:
inputtrain

age  gender  height  weight  ap_hi  ap_lo   cholesterol      gluc  \
61670  18351  female     166    70.0    103     70       chl_avg   glc_avg   
45252  22651  female     181    93.0    130     90  chl_aboveavg   glc_avg   
14569  16866    male     165    62.0    120     80       chl_avg   glc_avg   
29545  21801  female     157    70.0    110     80      chl_high   glc_avg   
47080  22387  female     162    66.0    120     90       chl_avg   glc_avg   
...      ...     ...     ...     ...    ...    ...           ...       ...   
5950   22677  female     163   105.0    140     80      chl_high  glc_high   
9939   21970  female     156    94.0    150     80  chl_aboveavg   glc_avg   
31223  20952    male     175   105.0    120     80       chl_avg  glc_high   
7007   19721  female     165   110.0    150     90      chl_high   glc_avg   
66628  18024  female     170    83.0    110     70       chl_avg   glc_avg   

       smoke  alco  active  
61670      0     0       1  
45252      0     0       0  
14569      0     0       1  
29545      0     0       1  
47080      0     0       1  
...      ...   ...     ...  
5950       0     0       1  
9939       0     0       1  
31223      0     0       0  
7007       0     0       1  
66628      0     0       1  

[54196 rows x 11 columns]

In [13]:
#scaling age (in days) (Numerical data) using Min-Max Scaler

from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()
scale.fit(inputtrain['age'].values.reshape(-1,1)) 

inputtrain_age = scale.transform(inputtrain[['age']])  
# inputcv_age = scale.transform(inputcv['age'].values.reshape(-1,1))
inputtest_age = scale.transform(inputtest['age'].values.reshape(-1,1))

/home/komal/anaconda3/envs/myenv/lib/python3.12/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


In [14]:
type(inputtrain_age)

numpy.ndarray

In [15]:
inputtrain_age.shape

(54196, 1)

In [16]:
# inputcv_age.shape

In [17]:
type(outputtrain)

numpy.ndarray

In [18]:
outputtrain.shape

(54196,)

In [19]:
# convert gender (categorical data) into One Hot Encoding

from sklearn.feature_extraction.text import CountVectorizer  

vec = CountVectorizer()
vec.fit(inputtrain['gender'].values)

inputtrain_gender = vec.transform(inputtrain['gender'].values)  
# inputcv_gender = vec.transform(inputcv['gender'].values)
inputtest_gender = vec.transform(inputtest['gender'].values)


In [20]:
inputtrain_gender

<54196x2 sparse matrix of type '<class 'numpy.int64'>'
	with 54196 stored elements in Compressed Sparse Row format>

In [21]:
type(inputtrain_gender)   #reshape(-1,1) convert sparse csr matrix into nparray

scipy.sparse._csr.csr_matrix

In [22]:
type(inputtrain_gender.toarray())

numpy.ndarray

In [23]:
inputtrain_gender.toarray()

array([[1, 0],
       [1, 0],
       [0, 1],
       ...,
       [0, 1],
       [1, 0],
       [1, 0]])

In [24]:
inputtrain_gender.toarray().shape

(54196, 2)

In [25]:
inputtrain_gender.shape

(54196, 2)

In [26]:
#scaling height (in cm) (Numerical data) using Min-Max Scaler

#from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()
scale.fit(inputtrain['height'].values.reshape(-1,1)) 

inputtrain_height = scale.transform(inputtrain['height'].values.reshape(-1,1))  
# inputcv_height = scale.transform(inputcv['height'].values.reshape(-1,1))
inputtest_height = scale.transform(inputtest['height'].values.reshape(-1,1))

In [27]:
type(inputtrain_height)

numpy.ndarray

In [28]:
inputtrain_height.shape

(54196, 1)

In [29]:
inputtrain_height

array([[0.52873563],
       [0.70114943],
       [0.51724138],
       ...,
       [0.63218391],
       [0.51724138],
       [0.57471264]])

In [30]:
#scaling weight (in kg) (Numerical data) using Min-Max Scaler

#from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()
scale.fit(inputtrain['weight'].values.reshape(-1,1)) 

inputtrain_weight = scale.transform(inputtrain['weight'].values.reshape(-1,1))  
# inputcv_weight = scale.transform(inputcv['weight'].values.reshape(-1,1))
inputtest_weight = scale.transform(inputtest['weight'].values.reshape(-1,1))

In [31]:
#scaling ap_lo (Numerical data) using Min-Max Scaler

#from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()
scale.fit(inputtrain['ap_lo'].values.reshape(-1,1)) 

inputtrain_ap_lo = scale.transform(inputtrain['ap_lo'].values.reshape(-1,1))  
# inputcv_ap_lo = scale.transform(inputcv['ap_lo'].values.reshape(-1,1))
inputtest_ap_lo = scale.transform(inputtest['ap_lo'].values.reshape(-1,1))

In [32]:
# convert cholesterol (categorical data) into One Hot Encoding

#from sklearn.feature_extraction.text import CountVectorizer  

vec = CountVectorizer()
vec.fit(inputtrain['cholesterol'].values)

inputtrain_cholesterol = vec.transform(inputtrain['cholesterol'].values)  
# inputcv_cholesterol = vec.transform(inputcv['cholesterol'].values)
inputtest_cholesterol = vec.transform(inputtest['cholesterol'].values)

In [33]:
# convert glucose (categorical data) into One Hot Encoding

#from sklearn.feature_extraction.text import CountVectorizer  

vec = CountVectorizer()
vec.fit(inputtrain['gluc'].values)

inputtrain_gluc = vec.transform(inputtrain['gluc'].values)  
# inputcv_gluc = vec.transform(inputcv['gluc'].values)
inputtest_gluc = vec.transform(inputtest['gluc'].values)

In [34]:
# smoke (categorical data) binary only 0/1 (Yes/No) hence no need to convert into One Hot Encoding 

#just converting sparse csr matrix form in np array form

inputtrain_smoke = inputtrain['smoke'].values.reshape(-1,1)
# inputcv_smoke = inputcv['smoke'].values.reshape(-1,1)
inputtest_smoke = inputtest['smoke'].values.reshape(-1,1)

In [35]:
# active, smoke, alcohol (categorical data) binary only 0/1 (Yes/No) hence no need to convert into One Hot Encoding 

#just converting sparse csr matrix form in np array form

inputtrain_active = inputtrain['active'].values.reshape(-1,1)
inputtest_active = inputtest['active'].values.reshape(-1,1)

inputtrain_smoke = inputtrain['smoke'].values.reshape(-1,1)
inputtest_smoke = inputtest['smoke'].values.reshape(-1,1)

inputtrain_alco = inputtrain['alco'].values.reshape(-1,1)
inputtest_alco = inputtest['alco'].values.reshape(-1,1)

In [36]:
inputtrain

age  gender  height  weight  ap_hi  ap_lo   cholesterol      gluc  \
61670  18351  female     166    70.0    103     70       chl_avg   glc_avg   
45252  22651  female     181    93.0    130     90  chl_aboveavg   glc_avg   
14569  16866    male     165    62.0    120     80       chl_avg   glc_avg   
29545  21801  female     157    70.0    110     80      chl_high   glc_avg   
47080  22387  female     162    66.0    120     90       chl_avg   glc_avg   
...      ...     ...     ...     ...    ...    ...           ...       ...   
5950   22677  female     163   105.0    140     80      chl_high  glc_high   
9939   21970  female     156    94.0    150     80  chl_aboveavg   glc_avg   
31223  20952    male     175   105.0    120     80       chl_avg  glc_high   
7007   19721  female     165   110.0    150     90      chl_high   glc_avg   
66628  18024  female     170    83.0    110     70       chl_avg   glc_avg   

       smoke  alco  active  
61670      0     0       1  
45252      0     0       0  
14569      0     0       1  
29545      0     0       1  
47080      0     0       1  
...      ...   ...     ...  
5950       0     0       1  
9939       0     0       1  
31223      0     0       0  
7007       0     0       1  
66628      0     0       1  

[54196 rows x 11 columns]

In [37]:
type(inputtrain_smoke)

numpy.ndarray

In [38]:
inputtrain_smoke.shape

(54196, 1)

In [39]:
type(inputtrain_active)

numpy.ndarray

In [40]:
inputtrain_active.shape

(54196, 1)

In [41]:
# stack arrays horizontally

from scipy.sparse import hstack

input_train = hstack((inputtrain_age, inputtrain_gender, inputtrain_height, inputtrain_weight, inputtrain_cholesterol, inputtrain_gluc, inputtrain_smoke , inputtrain_alco,inputtrain_active))
# cv = hstack((inputcv_age, inputcv_gender, inputcv_height, inputcv_weight, inputcv_cholesterol, inputcv_gluc, inputcv_active))
input_test = hstack((inputtest_age, inputtest_gender, inputtest_height, inputtest_weight, inputtest_cholesterol, inputtest_gluc,inputtest_smoke, inputtest_alco , inputtest_active))

In [42]:
input_train

<54196x14 sparse matrix of type '<class 'numpy.float64'>'
	with 376036 stored elements in COOrdinate format>

In [43]:
input_train = input_train.toarray()
input_test = input_test.toarray()

In [44]:
outputtrain

array([0, 1, 1, ..., 1, 1, 0])

In [45]:
input_train.shape   #input data

(54196, 14)

In [46]:
# cv.shape     #input data

In [47]:
input_test.shape     #input data

(13550, 14)

In [48]:
outputtrain.shape, outputtest.shape

((54196,), (13550,))

In [49]:
type(outputtrain), type(outputtest)

(numpy.ndarray, numpy.ndarray)

In [50]:
outputtrain = outputtrain.reshape(-1,1)
outputtest = outputtest.reshape(-1,1)

In [51]:
outputtrain = outputtrain.ravel()

In [52]:
type(outputtrain), type(outputtest)

(numpy.ndarray, numpy.ndarray)

In [53]:
outputtrain.shape, outputtest.shape

((54196,), (13550, 1))

In [54]:
###### Support Vector Machine

In [77]:
import numpy as np
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [56]:
svm_model = SVC(kernel = 'linear', random_state = 10)

In [57]:
svm_model.fit(input_train, outputtrain)

SVC(kernel='linear', random_state=10)

In [58]:
# make predictions on the test set.

In [59]:
y_pred = svm_model.predict(input_test)

In [60]:
#Evaluate the model's performance using various metrics

In [62]:
# calculate accuracy
accuracy = accuracy_score(y_pred,outputtest)

In [76]:
print(f'Accuracy : {accuracy*100 :.2f} %')

Accuracy : 64.69 %


In [78]:
# Confusion matrix
conf_matrix = confusion_matrix(outputtest, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

Confusion Matrix:
[[4707 2094]
 [2691 4058]]


In [79]:
# note that sum of all elements of the matrix is 13550

In [81]:
# Classification report
class_report = classification_report(outputtest, y_pred)
print('Classification Report:')
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.64      0.69      0.66      6801
           1       0.66      0.60      0.63      6749

    accuracy                           0.65     13550
   macro avg       0.65      0.65      0.65     13550
weighted avg       0.65      0.65      0.65     13550

